# Generated by Django 4.0.10 on 2024-09-27 15:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_postnew_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostNew',
            new_name='Post',
        ),
    ]
